### ISSUE TITLE
Provider query must not be a list

### ISSUE THREAD

**Issue by vschnei** [snakemake/snakemake-storage-plugin-s3#15]
**Snakemake version**
8.3.2

**Snakemake-storage-plugin-s3**
0.2.8

**Describe the bug**
Calling n-files located in a s3 storage throws a WorkflowError.
The problem is that the result of expand() is a list which is not a valid s3 query. A valid one would look like:
`query='s3://mybucket/myfile.txt` and not `query=['s3://mybucket/myfile.txt']`.

**Logs**
File ".../snakemake/storage.py", line 163, in _storage_object
    raise WorkflowError(
Error applying storage provider s3 (see https://snakemake.github.io/snakemake-plugin-catalog/plugins/storage/<snakemake_storage_plugin_s3.StorageProvider object at 0x7f2f79815490>.html). query ['s3://BUCKET_PATH/a_logo_size.txt', 's3://BUCKET_PATH/b_logo_size.txt', 's3://BUCKET_PATH/c_logo_size.txt', 's3://BUCKET_PATH/d_logo_size.txt'] is invalid: cannot be parsed as URL ('list' object has no attribute 'decode'))

**Additional context**
To overcome the problem one could use one of the suggestions:
1) Introduce anothe rule which copies the files to the compute infrastructure, modifies them and copies back to the s3 storage
2) query gets different typing.  Instead of `query: str` `query: Union[str, List(str)]`   in  snakemake_storage_plugin_s3/\_\_init__.py
   And adjustment of all interrelated methods etc.
   
@johanneskoester Not sure if there is anything else to consider regarding my second suggestion but if that is not the case I could try to make a PR for that issue.

**Comment by johanneskoester** [comment]
I think this solves your issue, right? https://github.com/snakemake/snakemake/pull/2674

**Comment by johanneskoester** [comment]
Now implemented in that PR, which is released today. thanks for pointing me to this!
