### ISSUE TITLE
Not download file durring dry-run

### ISSUE THREAD

**Issue by natir** [snakemake/snakemake-storage-plugin-s3#29]
When I run snakemake in dry-run, from my point of view snakemake should not download the files that are in the s3 storage.

This is particularly a problem when these files/objects are very large.

**Comment by johanneskoester** [comment]
Indeed, this is not intended and a bug.

**Comment by johanneskoester** [comment]
Here comes a fix: https://github.com/snakemake/snakemake/pull/3100
(just checked, the problem should have only occurred in workflows that contain checkpoints, right?)

**Comment by natir** [comment]
Yes it's exactly my use case !
